In [3]:
import numpy as np

def is_diagonally_dominant(matrix):
    """
    Checks if a given square matrix is diagonally dominant.

    A matrix A is diagonally dominant if, for every row i,
    the absolute value of the diagonal element A[i][i] is greater than or equal to
    the sum of the absolute values of the off-diagonal elements in that row.

    Args:
        matrix (list of lists or np.array): The square matrix to check.

    Returns:
        bool: True if the matrix is diagonally dominant, False otherwise.
    """
    # Convert to numpy array for easier calculations if it's a list of lists
    matrix = np.array(matrix)

    # Check if the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        print("Error: The input matrix must be square.")
        return False

    n = matrix.shape[0]

    for i in range(n):
        diagonal_element = abs(matrix[i, i])
        row_sum_off_diagonal = np.sum(abs(matrix[i, :])) - diagonal_element

        if diagonal_element < row_sum_off_diagonal:
            return False

    return True

In [4]:
# Example 1: A diagonally dominant matrix
matrix1 = [
    [4, -1, 0],
    [-1, 4, -1],
    [0, -1, 4]
]

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(matrix1)}")
print("Display the matrix:")
print(np.array(matrix1))

print("\n" * 2)

# Example 2: A non-diagonally dominant matrix
matrix2 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(f"Is the matrix diagonally dominant? {is_diagonally_dominant(matrix2)}")
print("Display the matrix:")
print(np.array(matrix2))

Is the matrix diagonally dominant? True
Display the matrix:
[[ 4 -1  0]
 [-1  4 -1]
 [ 0 -1  4]]



Is the matrix diagonally dominant? False
Display the matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
